### ISSUE TITLE
MudSelectExtended incorrect size compared to MudSelect

### ISSUE THREAD

**Issue by Hiden46** [CodeBeamOrg/CodeBeam.MudExtensions#353]
Hi, I noticed that the dimensions of the **MudSelectExtended** component do not reflect those of the MudBlazor **MudSelect** component.

I used attributes 

`Margin="Margin.Dense"
Dense="true"`

in both components but they are not the same.
The left component is **MudSelectExtended**, the right one is **MudSelect**.

![bug-MudSelectExtended](https://github.com/CodeBeamOrg/CodeBeam.MudBlazor.Extensions/assets/63296687/f08b8c89-5f73-46aa-bdfb-d80cda407862)

**Comment by michallabuzsybilla** [comment]
Up, I am facing the same problem. Any workaround ?

**Comment by mckaragoz** [comment]
The issue should be fixed with the latest (8.1.0) release. If you encounter any other problem, please reopen this issue.

**Comment by Hiden46** [comment]
Hi @mckaragoz it's me again. 
We just updated our project with the latest release but we still see the problem.
We noticed that the size is correct once we select the value.

Before value selection

![Image](https://github.com/user-attachments/assets/3d533cdf-54c7-4efc-9067-5dfc6e4f69ea)

After value selection

![Image](https://github.com/user-attachments/assets/2848d39e-79dc-4625-ad95-797f086a5ce6)

For more info, we use `MudSelectExtended `also with `MudSelectItemGroupExtended`

**Comment by mckaragoz** [comment]
It look like dense one, you mean empty dense select is bigger than the core select?

**Comment by Hiden46** [comment]
Yes, the left component is the `MudSelectExtended `which when it has no value is larger than `MudSelect` (the one on the right).

That's my code for the `MudSelectExtended `:

```
<MudSelectExtended 
	T="User" 
	Label="User"
	Variant="Variant.Outlined"
	Margin="Margin.Dense"
	Dense="true"
	MultiSelection="false">
	<MudSelectItemGroupExtended T="User" Style="font-weight:900" Text="@item.Department.Description" Sticky="false" Nested="false" InitiallyExpanded="true">
		<MudSelectItemExtended Value="@user">User 1</MudSelectItemExtended>
	</MudSelectItemGroupExtended>
</MudSelectExtended>				
```


And this for the core `MudSelect`:

```
<MudSelect 
	T="TimeTrackingTypeEntity" 
	Variant="Variant.Outlined"
	Label="Type"
	Margin="Margin.Dense"
	Dense="true">
		<MudSelectItem T="TimeTrackingTypeEntity" Value="@item">Type</MudSelectItem>
</MudSelect>
```

**Comment by mckaragoz** [comment]
Did you refresh cache (Ctrl+f5)? I don't see any difference on my local. Tried with both dense and Margin.Dense parameters.

**Comment by mckaragoz** [comment]
There was a size issue when placeholder set and fixed. Will be available on next release.
